### ISSUE TITLE
Specify installed CakePHP version

### ISSUE THREAD

**Issue by josegonzalez** [CakeDC/oven#10]
We should allow devs to install a specific version of cake - 3.x+ - but also warn them when it isn't the latest stable.

**Comment by phpnut** [comment]
I think allowing installing master, Beta and RC releases is fine. I prefer not to allow anything that is below master though. We are wanting users to adopt the latest and allowing access to prior releases with one click goes against that. If they want an older version they should be using CLI.

**Comment by josegonzalez** [comment]
Well we want newer BETA and RC that are newer than latest stable. Latest stable should be what we install instead of "master" I'd think.

How do we want to expose this information to oven so it stays up to date? Other than parsing the packagist api, not sure what we should do here.

**Comment by phpnut** [comment]
@josegonzalez I was using master as latest stable.
I propose the following.
Latest tagged release
Latest Beta
Latest RC
