### ISSUE TITLE
Database configuration fails when host is numeric

### ISSUE THREAD

**Issue by joshwyrick** [CakeDC/oven#14]
In the DB config form fields, if you input a host that is numeric, then `app.php` configuration gets mangled at line 220. I'm assuming the problem is the pattern in `DATASOURCE_REGEX`, line 32 in `oven.php`. See screenshots below.

**Error:** 

After attempting an IP, then a Rackspace host with a numeric sub-domain, I tried simply "42" to see what would happen. Screenshot is result. All attempts resulted in similar code removal.

![error](https://cloud.githubusercontent.com/assets/12661899/24416144/cac6bbf0-13b1-11e7-95fc-c08167c8a4b7.png)

**Default:**

![default](https://cloud.githubusercontent.com/assets/12661899/24416143/cac5cf74-13b1-11e7-8fc9-bb44d81e2596.png)

**Comment by andrej-griniuk** [comment]
Thanks for reporting. Fixed.
