### ISSUE TITLE
Can't install to the root folder!

### ISSUE THREAD

**Issue by vamcart** [CakeDC/oven#18]
Try to install to the root folder http://localhost , not http://localhost/app
Can't install.

Try to install with app dir empty value and get the error:

Warning: require(/home/vamshop-en/www/vendor/autoload.php): failed to open stream: No such file or directory in /home/vamshop-en/www/webroot/index.php on line 27

How to install to the root folder?!

![screenshot from 2017-06-25 22-55-57](https://user-images.githubusercontent.com/3618501/27519320-ae9a4940-59f9-11e7-828d-26780f193ab7.png)
![screenshot from 2017-06-25 22-56-25](https://user-images.githubusercontent.com/3618501/27519323-b17d11a6-59f9-11e7-83ac-fcb55f49731b.png)

**Comment by julianmojico** [comment]
Not really understand your problem....probably filesystem permissions....my advise is :You should bake your cake in /var/www/html/
Copy your oven.php
Give full permissons : sudo chmod 775 /var/www/html
And load oven.php

**Comment by vamcart** [comment]
File and directory permissions correct.

I can't.
I have http://localhost domain and html folder /var/www/
I want to install Over to http://localhost

I can install to http://localhost/app_name , but not http://localhost

**Comment by andrej-griniuk** [comment]
This behaviour is correct, you can't install it to the directory where oven.php is placed.
The script is using `composer create-project` and it can only be done for an empty dir.
