### ISSUE TITLE
Undefined method Cake\Utility\Security::setSalt()

### ISSUE THREAD

**Issue by Tomicapo** [CakeDC/oven#19]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.13.
* Platform and Target: Apache 2.4.18, Xampp Windows, PHP 7.0.8.

### What you did
Copy oven.php. Installed choosing version 3.4.13. 

### What happened
I got this error browsing the site: Call to undefined method Cake\Utility\Security::setSalt()

### What you expected to happen
The welcome page should be displayed.

**Comment by andrej-griniuk** [comment]
Fixed. Thanks for reporting!
