### ISSUE TITLE
database config

### ISSUE THREAD

**Issue by aramis-it** [CakeDC/oven#2]

**Comment by phpnut** [comment]
@infokani Can you provide more details to this ticket? What exactly do you want?

**Comment by infokani** [comment]
Enter database details and project name in the beginning

![english 1](https://cloud.githubusercontent.com/assets/169289/22046744/cabb8224-dd5d-11e6-8d56-14e2da42be1c.jpg)

**Comment by aramis-it** [comment]
Enter database details and project name before bake
![english 2](https://cloud.githubusercontent.com/assets/169289/22046780/09a85b7e-dd5e-11e6-9784-9bb40e65ae9b.jpg)
