### ISSUE TITLE
root folder name

### ISSUE THREAD

**Issue by aramis-it** [CakeDC/oven#3]

**Comment by phpnut** [comment]
@infokani Can you provide more details to this ticket? What exactly do you want?

**Comment by aramis-it** [comment]
Choose project name

![english](https://cloud.githubusercontent.com/assets/169289/22046608/b7098b1e-dd5c-11e6-8e6f-264cc67e3b43.jpg)

**Comment by andrej-griniuk** [comment]
Should we allow installing to any path? (then we don't know what's the app URL)
Any path within current path?
Non-empty dirs?

**Comment by aramis-it** [comment]
Oven installs within current path
![untitled](https://cloud.githubusercontent.com/assets/169289/22203753/7b3961a8-e1a9-11e6-997d-cf265ee320a2.png)

**Comment by andrej-griniuk** [comment]
So do we need to have the ability to install to any path? Or just current path, but custom dir name would be enough?
And what about installing to current dir, without a subdir (./)?

**Comment by aramis-it** [comment]
Current path enough for me

**Comment by aramis-it** [comment]
Someone created new issue almost same as mine 
Issue name is "Centralized installation location"

**Comment by kyleweishaupt** [comment]
Installing without a subdirectory could be helpful as well, but +1 for at least changing the app folder name. It helps a lot when you're just simply installing under an htdocs directory in Apache containing multiple projects.
