### ISSUE TITLE
bake commands

### ISSUE THREAD

**Issue by aramis-it** [CakeDC/oven#4]

**Comment by phpnut** [comment]
@infokani Can you provide more details to this ticket? What exactly do you want?

**Comment by aramis-it** [comment]
![english 3](https://cloud.githubusercontent.com/assets/169289/22047161/38696adc-dd60-11e6-8cb4-77b8c3594416.jpg)

**Comment by spencerthayer** [comment]
This would be amazing. Any chances?

**Comment by andrej-griniuk** [comment]
So as now we have Mixer this functionality has a better fit there. Opened a ticket in Mixer repo.

**Comment by andrej-griniuk** [comment]
@infokani @spencerthayer we've just release Mixer 1.1 (https://github.com/CakeDC/mixer/releases/tag/1.1.0) where this has been implemented. Check it out!
