### ISSUE TITLE
Use system wide Composer

### ISSUE THREAD

**Issue by narendravaghela** [CakeDC/oven#5]
Is it possible to use system wide installed composer instead of installing it each time we run the oven.php?

**Comment by phpnut** [comment]
@narendravaghela Originally we had this using local composer and decided to make it universal on the first release. We do plan to add this back in future version. That you for confirming this would be a good enhancement.

**Comment by Tomicapo** [comment]
I assume there should be a way to try first using already installed composer and install if that fails.
