### ISSUE TITLE
Offer to install some of the popular plugins

### ISSUE THREAD

**Issue by lorenzo** [CakeDC/oven#8]
it would be nice to also execute composer commands and `bin/cake plugin load` for a list of popular plugins that the user can choose from. Some suggestions:

* bootstrap-ui
* cakedec/users
* crud and crud-api
* middleware authentication

**Comment by andrej-griniuk** [comment]
That's definitely on our list

**Comment by andrej-griniuk** [comment]
So now we have https://github.com/cakedc/mixer for installing plugins and Mixer can be installed from Oven.
